export const reports: Record<string, { year: string; season: string }> = {
    "2007.5": { year: "2007", season: "Fall" },
    "2008.5": { year: "2008", season: "Fall" },
    "2009.5": { year: "2009", season: "Fall" },
    "2010.5": { year: "2010", season: "Fall" },
    "2011.5": { year: "2011", season: "Fall" },
    "2012.5": { year: "2012", season: "Fall" },
    "2013.5": { year: "2013", season: "Fall" },
    "2014.5": { year: "2014", season: "Fall" },
    "2015.5": { year: "2015", season: "Fall" },
    "2016.5": { year: "2016", season: "Fall" },
    "2017.5": { year: "2017", season: "Fall" },
    "2018.5": { year: "2018", season: "Fall" },
    "2019.5": { year: "2019", season: "Fall" },
    "2020.5": { year: "2020", season: "Fall" },
    "2021.5": { year: "2021", season: "Fall" },
    "2022.5": { year: "2022", season: "Fall" },
    "2023.5": { year: "2023", season: "Fall" },
    "2024.5": { year: "2024", season: "Fall" },
    "2025": { year: "2025", season: "Spring" },
    
}

export const clubs = {
    "ATL": "Atlanta United",
    "CHI": "Chicago Fire",
    "CHV": "Chivas USA",
    "CLB": "Columbus Crew",
    "COL": "Colorado Rapids",
    "DAL": "FC Dallas",
    "DC": "DC United",
    "HOU": "Houston Dynamo",
    "KC": "Sporting Kansas City",
    "LA": "LA Galaxy",
    "LAFC": "LAFC",
    "MNUFC": "Minnesota United",
    "MTL": "CF Montreal",
    "NE": "New England Revolution",
    "NYCFC": "New York City FC",
    "NYRB": "New York Red Bulls",
    "NY": "New York Red Bulls",
    "ORL": "Orlando City SC",
    "PHI": "Philadelphia Union",
    "POR": "Portland Timbers",
    "RSL": "Real Salt Lake",
    "SEA": "Seattle Sounders FC",
    "SJ": "San Jose Earthquakes",
    "TOR": "Toronto FC",
    "TFC": "Toronto FC",
    "VAN": "Vancouver Whitecaps",
    "POOL": "MLS Pool",
    "Pool": "MLS Pool",
    "": "MLS Pool",
    "None": "MLS Pool"
}
