export const reports: Record<string, { year: string; season: string }> = {
    "2007.5": { year: "2007", season: "Fall" },
    "2008.5": { year: "2008", season: "Fall" },
    "2009.5": { year: "2009", season: "Fall" },
    "2010.5": { year: "2010", season: "Fall" },
    "2011.5": { year: "2011", season: "Fall" },
    "2012.5": { year: "2012", season: "Fall" },
    "2013.5": { year: "2013", season: "Fall" },
    "2014.5": { year: "2014", season: "Fall" },
    "2015.5": { year: "2015", season: "Fall" },
    "2016.5": { year: "2016", season: "Fall" },
    "2017.5": { year: "2017", season: "Fall" },
    "2018.5": { year: "2018", season: "Fall" },
    "2019.5": { year: "2019", season: "Fall" },
    "2020.5": { year: "2020", season: "Fall" },
    "2021.5": { year: "2021", season: "Fall" },
    "2022.5": { year: "2022", season: "Fall" },
    "2023.5": { year: "2023", season: "Fall" },
    "2024.5": { year: "2024", season: "Fall" },
    "2025": { year: "2025", season: "Spring" },
    
}

export const clubs: Record<string, { clubName: string; yearFirst: number; yearFinal: number; totalBaseSal: number; totalGuarComp: number}> = { 
    "ATX" : { clubName: "Austin FC", yearFirst: 2021, yearFinal: 0, totalBaseSal: 0, totalGuarComp: 0 },
    "ATL": { clubName: "Atlanta United", yearFirst: 2017, yearFinal: 0, totalBaseSal: 0, totalGuarComp: 0 },
    "CLT": { clubName: "Charlotte FC", yearFirst: 2022, yearFinal: 0, totalBaseSal: 0, totalGuarComp: 0 },
    "CHI": { clubName: "Chicago Fire", yearFirst: 1998, yearFinal: 0, totalBaseSal: 0, totalGuarComp: 0 },
    "CHV": { clubName: "Chivas USA", yearFirst: 2005, yearFinal: 2014, totalBaseSal: 0, totalGuarComp: 0 },
    "CIN": { clubName: "FC Cincinnati", yearFirst: 2019, yearFinal: 0, totalBaseSal: 0, totalGuarComp: 0 },
    "CLB": { clubName: "Columbus Crew", yearFirst: 1996, yearFinal: 0, totalBaseSal: 0, totalGuarComp: 0 },
    "COL": { clubName: "Colorado Rapids", yearFirst: 1996, yearFinal: 0, totalBaseSal: 0, totalGuarComp: 0 },
    "DAL": { clubName: "FC Dallas", yearFirst: 1996, yearFinal: 0, totalBaseSal: 0, totalGuarComp: 0 },
    "DC": { clubName: "DC United", yearFirst: 1996, yearFinal: 0, totalBaseSal: 0, totalGuarComp: 0 },
    "HOU": { clubName: "Houston Dynamo", yearFirst: 2006, yearFinal: 0, totalBaseSal: 0, totalGuarComp: 0 },
    "KC": { clubName: "Sporting Kansas City", yearFirst: 1996, yearFinal: 0, totalBaseSal: 0, totalGuarComp: 0 },
    "LA": { clubName: "LA Galaxy", yearFirst: 1996, yearFinal: 0, totalBaseSal: 0, totalGuarComp: 0 },
    "LAFC": { clubName: "LAFC", yearFirst: 2018, yearFinal: 0, totalBaseSal: 0, totalGuarComp: 0 },
    "MIA": { clubName: "Inter Miami", yearFirst: 2020, yearFinal: 0, totalBaseSal: 0, totalGuarComp: 0 },
    "MNUFC": { clubName: "Minnesota United", yearFirst: 2017, yearFinal: 0, totalBaseSal: 0, totalGuarComp: 0 },
    "MTL": { clubName: "CF Montreal", yearFirst: 2012, yearFinal: 0, totalBaseSal: 0, totalGuarComp: 0 },
    "NSH": { clubName: "Nashville SC", yearFirst: 2020, yearFinal: 0, totalBaseSal: 0, totalGuarComp: 0 },
    "NE": { clubName: "New England Revolution", yearFirst: 1996, yearFinal: 0, totalBaseSal: 0, totalGuarComp: 0 },
    "NYC": { clubName: "New York City FC", yearFirst: 2015, yearFinal: 0, totalBaseSal: 0, totalGuarComp: 0 },
    "RBNY": { clubName: "New York Red Bulls", yearFirst: 1996, yearFinal: 0, totalBaseSal: 0, totalGuarComp: 0 },
    "ORL": { clubName: "Orlando City SC", yearFirst: 2015, yearFinal: 0, totalBaseSal: 0, totalGuarComp: 0 },
    "PHI": { clubName: "Philadelphia Union", yearFirst: 2010, yearFinal: 0, totalBaseSal: 0, totalGuarComp: 0 },
    "POR": { clubName: "Portland Timbers", yearFirst: 2011, yearFinal: 0, totalBaseSal: 0, totalGuarComp: 0 },
    "RSL": { clubName: "Real Salt Lake", yearFirst: 2005, yearFinal: 0, totalBaseSal: 0, totalGuarComp: 0 },
    "STL": { clubName: "St. Louis City SC", yearFirst: 2023, yearFinal: 0, totalBaseSal: 0, totalGuarComp: 0 },
    "SEA": { clubName: "Seattle Sounders FC", yearFirst: 2009, yearFinal: 0, totalBaseSal: 0, totalGuarComp: 0 },
    "SD": { clubName: "San Diego FC", yearFirst: 2025, yearFinal: 0, totalBaseSal: 0, totalGuarComp: 0 },
    "SJ": { clubName: "San Jose Earthquakes", yearFirst: 1996, yearFinal: 0, totalBaseSal: 0, totalGuarComp: 0 },
    "TOR": { clubName: "Toronto FC", yearFirst: 2007, yearFinal: 0, totalBaseSal: 0, totalGuarComp: 0 },
    "VAN": { clubName: "Vancouver Whitecaps", yearFirst: 2011, yearFinal: 0, totalBaseSal: 0, totalGuarComp: 0 },
    "MLS": { clubName: "MLS Pool", yearFirst: 0, yearFinal: 0, totalBaseSal: 0, totalGuarComp: 0 },
}

export const CURRENT_YEAR = "2025"
